# @format

apiVersion: v2
name: saleor-core
description: A Helm chart for deploying the saleor core application in Kubernetes
type: application
version: 0.1.1
appVersion: 2.11.4
kubeVersion: ""
keywords:
  - saleor
  - ecommerce
  - graphql
  - django
home: https://github.com/eirenauts/saleor-k8s
sources:
  - https://github.com/mirumee/saleor
  - https://github.com/eirenauts/saleor-k8s
maintainers:
  - name: Stephen Moloney
    email: stephen@stephenmoloney.com
    url: stephenmoloney.com
